In [5]:
from atari_rl.il.expert_dataset import ExpertDataset
IMAGE_SIZE = 84
FRAME_STACK_SIZE = 4
NUM_ACTIONS = 3
obs_shape = (FRAME_STACK_SIZE, IMAGE_SIZE, IMAGE_SIZE)
EXPERT_NAME = "expert_dataset_239_102738"
expert_dataset = ExpertDataset(obs_shape, NUM_ACTIONS, expert_name=EXPERT_NAME)


In [6]:
actions = expert_dataset.load_actions()
actions

array([1, 1, 1, ..., 0, 0, 0], shape=(102738,), dtype=int32)

In [7]:
import numpy as np
counts = np.bincount(actions)
counts

array([34246, 34246, 34246])

In [8]:
total = len(actions)
percentages = (counts / total) * 100
percentages


array([33.33333333, 33.33333333, 33.33333333])