In [1]:
from atari_rl.iql.expert_dataset import ExpertDataset
IMAGE_SIZE = 84
FRAME_STACK_SIZE = 4
NUM_ACTIONS = 3
obs_shape = (FRAME_STACK_SIZE, IMAGE_SIZE, IMAGE_SIZE)
EXPERT_NAME = "iql_expert_dataset_235_1479"
expert_dataset = ExpertDataset(obs_shape, NUM_ACTIONS, expert_name=EXPERT_NAME)


In [2]:
actions = expert_dataset.load_actions()
actions

array([1, 1, 1, ..., 0, 0, 0], shape=(1479,), dtype=int32)

In [3]:
import numpy as np
counts = np.bincount(actions)
counts

array([493, 493, 493])

In [4]:
total = len(actions)
percentages = (counts / total) * 100
percentages


array([33.33333333, 33.33333333, 33.33333333])